### ISSUE TITLE
Add license to the project

### ISSUE THREAD

**Issue by alfabetacain** [ohgoditspotato/atreides_mentat#12]
I'm playing around with a simpler toy version of this project and I noticed that the project currently has no explicit license.
My toy project is definitely derivative (I really like the design of your site 😄 ), so that would violate your copyright. 

Would it be possible to add a more permissive license [(https://choosealicense.com/)](https://choosealicense.com/) to this project so I can publish my own version (with a reference to this project)? 😄 

Thanks in advance!

**Comment by ohgoditspotato** [comment]
Hi @alfabetacain
Sorry I've only just replied to your message  -I've added a license to the project (MIT) so please feel free to do with it as you wish - I'm glad you like it!
Thanks,
Robert
