### ISSUE TITLE
Unknown Cards to Known Cards

### ISSUE THREAD

**Issue by Pyko1** [ohgoditspotato/atreides_mentat#2]
There Seems to be no way to change unknown card in to a known card, as only option is to remove it, which forces you to choose a card to discard, instead of choosing card to replace.

Also a way to restore individual cards from the discards back to the deck would be helpful, as misclicks do happen.

**Comment by ohgoditspotato** [comment]
Ah, those are really good points! I will implement both. There is an "undo" function at the top right of the page, so if you accidentally discard something you can undo it - but it would be handy like you say to be able to put cards back in the deck.

**Comment by ohgoditspotato** [comment]
Implemented in the last two patches.
To force the page to update - if you're using a browser to use the page - you'll have to refresh the page - then close all open windows and re-open it. If you're using the phone app, you'll need to "force stop" the app and then re-open it to force an update.
