### ISSUE TITLE
Wrong card names

### ISSUE THREAD

**Issue by Pyko1** [ohgoditspotato/atreides_mentat#6]
I believe kriminon is actually called as Ellaca Drug and Slip-Tip is Slip Tip on GF9 Dune.
![dune_all_cards](https://user-images.githubusercontent.com/12048747/75595893-e615bd00-5a96-11ea-9a91-1b5daee30952.png)

This is from Tabletop simulator, but one of the poison weapons did have different name on my friends GF9 Dune, so im pretty sure it was indeed Kriminon / Ellaca Drug.

**Comment by ohgoditspotato** [comment]
Good spot, I will update the names!
