### ISSUE TITLE
Harkonnen Karama ability

### ISSUE THREAD

**Issue by Pyko1** [ohgoditspotato/atreides_mentat#7]
No way really to do harkonnen karama abilty card swap, without starting a new game. and then failing with half of the discards and shuffles and ending up with unknown cards on hands that should be available in deck/etc.

**Comment by ohgoditspotato** [comment]
Ah crud. It might actually be better to get rid of the odds tracking of unknown cards. Although the probability calculating is nice, it just makes it much more complicated to actually use the app - and if you mess something up it's a real faff to put it right...

**Comment by Pyko1** [comment]
Maybe add a button to reset probability calculations instead?

Even tho, dont think anything else really messes the probabilities up that much besides attempting to do the harkonen karama swap manually.

**Comment by ohgoditspotato** [comment]
I added the ability to disable the tracking mid game - in case you need to account for a harkonnen card swap. This just allows you to assign any card again - and does not update the probablities for unknown cards based on the  cards in play.
So if Harkonnen is in the game - you can play normally - and then if they do a card swap - you can "eject" from the tracking and just play from there - sorry I couldn't think of a better solution to this!

**Comment by ohgoditspotato** [comment]
Oh - and card  tracking can also just be disabled from the outset - for people who feel it might be a bit cheesy :)
