### ISSUE TITLE
Expansion Content Update

### ISSUE THREAD

**Issue by 0rigam3r** [ohgoditspotato/atreides_mentat#9]
@ohgoditspotato , Might I suggest adding the new treachery cards and factions from the expansion? Perhaps have a toggle that allows you to optionally add the new cards? Thanks! Keep up the great work.

**Comment by ohgoditspotato** [comment]
Hi @0rigam3r - that's a good idea! However I'm afraid I don't own the expansion so I don't have the cards to hand. However - if you were willing to list the expansion cards here I'd be happy to add them into the app. Thanks!

**Comment by 0rigam3r** [comment]
Thanks for responding! Here's a link to the rulebook should you need it
(https://www.gf9.com/Portals/0/Documents/GF9/IxianAndTleilaxuRulebook.pdf)

### **_Here's a list of the cards:_**

- **Artillery Strike - Weapon - Special**
Play as part of your Battle Plan.
Kills both leaders (no spice is paid for them).
Both players may use Shields to protect their leader against the Artillery Strike.
Surviving (shielded) leaders do not count towards the battle total; the side that dialed higher wins the battle.
   
- **Poison Tooth - Weapon - Special**
Play as part of your Battle Plan.
Kills both leaders, and is not stopped by a Snooper
After seeing the battle results, you may choose not to use this weapon.

- **Weirding Way - Weapon - Defense - Special**
Play as part of your Battle Plan.
Counts as a projectile weapon, unless played with another weapon. In that case, it counts as a projectile defense.
You may keep this card if you win this battle.

- **Chemistry - Defense - Weapon - Special**
Play as part of your Battle Plan.
Counts as a poison defense, unless played with another defense. In that case, it counts as a poison weapon.
You may keep this card if you win this battle.

- **Poison Blade - Weapon - Special**
Play as part of your Battle Plan.
This weapon counts as both projectile and poison.
You may keep this card if you win this battle.

- **Shield Snooper - Defense - Special**
Play as part of your Battle Plan.
Counts as both a Shield (projectile defense) and Snooper (poison defense).
You may keep this card if you win this battle.

- **Hunter Seeker - Weapon - Projectile**
Play as part of your Battle Plan.
Kills opponent's leader before battle is resolved. Opponent may protect leader with a Shield.
You may keep this card if you win this battle.

- **Basilia Weapon - Weapon - Poison**
Play as part of your Battle Plan.
Kills opponent's leader before battle is resolved. Opponent may protect leader with a Snooper.
You may keep this card if you win this battle.

- **Kull Wahad - Worthless Card**
Play as part of your Battle Plan, in place of a weapon, defense, or both.
This card has no value in play, and you can discard it only by playing it in your Battle Plan.

- **Harvester - Spice Blow - Special**
Play just after a spice blow comes up.
Doubles the spice blow. Place double the amount of spice in the territory.

- **Thumper - Spice Blow - Special**
Play at beginning of Spice Blow Phase instead of revealing the next Spice Blow card. Causes a Sandworm to appear.
Play proceeds as though Shai-Hulud has been revealed.

- **Amal - Special**
At the beginning of any phase, cause all players to discard half of the spice behind their shields, rounded up, to the Spice Bank.

- **Shield - Defense - Projectile**
Play as part of your Battle Plan.
Protects your leader from a projectile weapon in this battle.
You may keep this card if you win this battle.

- **Snooper - Defense - Poison**
Play as part of your Battle Plan.
Protects your leader from a poison weapon in this battle.
You may keep this card if you win this battle.


I don't know if you want to rename your lasgun to be special weapon instead of unique weapon. There just is a lot of new cards and card types in this expansion

**Comment by 0rigam3r** [comment]
![IMG_20200611_154215__01](https://user-images.githubusercontent.com/60159374/86412895-8833f480-bc85-11ea-902d-f98b4260228b.jpg)

**Comment by Ortimer** [comment]
This should be solved by this PR https://github.com/ohgoditspotato/atreides_mentat/pull/11
